### ISSUE TITLE
Investigate issues where bundler gets stuck on not knowing about an existing module

### ISSUE THREAD

**Issue by pachet** [burninggarden/burninggarden#44]
Sometimes when you remove a module dependency from a file, the bundler gets confused and thinks that it can't find the module you removed if it's used elsewhere. Why this is, I have no idea.

**Comment by inconclusive** [comment]
why this is, i have no idea

**Comment by pachet** [comment]
This is fixed now. It was because we continually decremented the `open dependency count`, but never reincremented. So files would fall out of the index but were never readded.
